using System;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Model {

  /// <summary>
  /// The mandate information for the Credit Card, Credit Card Reference Transaction, ACH, or Bank Transfer payment method.
  /// </summary>
  [DataContract]
  public class Mandate {
    /// <summary>
    /// Identifier of the single- or multi-use mandate generated by the payment gateway.
    /// </summary>
    /// <value>Identifier of the single- or multi-use mandate generated by the payment gateway.</value>
    [DataMember(Name="id", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "id")]
    public string Id { get; set; }

    /// <summary>
    /// Reason for the mandate.
    /// </summary>
    /// <value>Reason for the mandate.</value>
    [DataMember(Name="reason", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "reason")]
    public string Reason { get; set; }

    /// <summary>
    /// The status of the mandate, which indicates whether it can be used to initiate a payment.
    /// </summary>
    /// <value>The status of the mandate, which indicates whether it can be used to initiate a payment.</value>
    [DataMember(Name="state", EmitDefaultValue=false)]
    [JsonProperty(PropertyName = "state")]
    public string State { get; set; }


    /// <summary>
    /// Get the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()  {
      var sb = new StringBuilder();
      sb.Append("class Mandate {\n");
      sb.Append("  Id: ").Append(Id).Append("\n");
      sb.Append("  Reason: ").Append(Reason).Append("\n");
      sb.Append("  State: ").Append(State).Append("\n");
      sb.Append("}\n");
      return sb.ToString();
    }

    /// <summary>
    /// Get the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson() {
      return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

}
}
