/*
 * Quickstart API Reference
 *
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.   To use the Quickstart API, you must have the following features enabled on your tenant:   * [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)  * [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)  To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).  We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.  
 *
 * OpenAPI spec version: 2024-01-10
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ZIP2Go.Models
{
    /// <summary>
    /// Accounting configuration if you have Zuora Revenue enabled.
    /// </summary>
    [DataContract]
    public partial class OrderLineItemRevenue : IEquatable<OrderLineItemRevenue>
    { 
        /// <summary>
        /// If set to &#x60;true&#x60;, any associated billing document items are excluded from the revenue accounting.
        /// </summary>
        /// <value>If set to &#x60;true&#x60;, any associated billing document items are excluded from the revenue accounting.</value>

        [DataMember(Name="exclude_item_billing_from_revenue_accounting")]
        public bool? ExcludeItemBillingFromRevenueAccounting { get; set; }

        /// <summary>
        /// If set to &#x60;true&#x60;, any associated subscription items are excluded from the revenue accounting.
        /// </summary>
        /// <value>If set to &#x60;true&#x60;, any associated subscription items are excluded from the revenue accounting.</value>

        [DataMember(Name="exclude_item_booking_from_revenue_accounting")]
        public bool? ExcludeItemBookingFromRevenueAccounting { get; set; }

        /// <summary>
        /// An active accounting code in your Zuora chart of accounts.
        /// </summary>
        /// <value>An active accounting code in your Zuora chart of accounts.</value>

        [DataMember(Name="adjustment_revenue_account")]
        public string AdjustmentRevenueAccount { get; set; }

        /// <summary>
        /// An active accounting code in your Zuora chart of accounts.
        /// </summary>
        /// <value>An active accounting code in your Zuora chart of accounts.</value>

        [DataMember(Name="contract_recognized_revenue_account")]
        public string ContractRecognizedRevenueAccount { get; set; }

        /// <summary>
        /// An active accounting code in your Zuora chart of accounts.
        /// </summary>
        /// <value>An active accounting code in your Zuora chart of accounts.</value>

        [MaxLength(100)]
        [DataMember(Name="deferred_revenue_account")]
        public string DeferredRevenueAccount { get; set; }

        /// <summary>
        /// An active accounting code in your Zuora chart of accounts.
        /// </summary>
        /// <value>An active accounting code in your Zuora chart of accounts.</value>

        [MaxLength(100)]
        [DataMember(Name="recognized_revenue_account")]
        public string RecognizedRevenueAccount { get; set; }

        /// <summary>
        /// The revenue recognition rule for the order line item.
        /// </summary>
        /// <value>The revenue recognition rule for the order line item.</value>

        [DataMember(Name="revenue_recognition_rule_name")]
        public string RevenueRecognitionRuleName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrderLineItemRevenue {\n");
            sb.Append("  ExcludeItemBillingFromRevenueAccounting: ").Append(ExcludeItemBillingFromRevenueAccounting).Append("\n");
            sb.Append("  ExcludeItemBookingFromRevenueAccounting: ").Append(ExcludeItemBookingFromRevenueAccounting).Append("\n");
            sb.Append("  AdjustmentRevenueAccount: ").Append(AdjustmentRevenueAccount).Append("\n");
            sb.Append("  ContractRecognizedRevenueAccount: ").Append(ContractRecognizedRevenueAccount).Append("\n");
            sb.Append("  DeferredRevenueAccount: ").Append(DeferredRevenueAccount).Append("\n");
            sb.Append("  RecognizedRevenueAccount: ").Append(RecognizedRevenueAccount).Append("\n");
            sb.Append("  RevenueRecognitionRuleName: ").Append(RevenueRecognitionRuleName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((OrderLineItemRevenue)obj);
        }

        /// <summary>
        /// Returns true if OrderLineItemRevenue instances are equal
        /// </summary>
        /// <param name="other">Instance of OrderLineItemRevenue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrderLineItemRevenue other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ExcludeItemBillingFromRevenueAccounting == other.ExcludeItemBillingFromRevenueAccounting ||
                    ExcludeItemBillingFromRevenueAccounting != null &&
                    ExcludeItemBillingFromRevenueAccounting.Equals(other.ExcludeItemBillingFromRevenueAccounting)
                ) && 
                (
                    ExcludeItemBookingFromRevenueAccounting == other.ExcludeItemBookingFromRevenueAccounting ||
                    ExcludeItemBookingFromRevenueAccounting != null &&
                    ExcludeItemBookingFromRevenueAccounting.Equals(other.ExcludeItemBookingFromRevenueAccounting)
                ) && 
                (
                    AdjustmentRevenueAccount == other.AdjustmentRevenueAccount ||
                    AdjustmentRevenueAccount != null &&
                    AdjustmentRevenueAccount.Equals(other.AdjustmentRevenueAccount)
                ) && 
                (
                    ContractRecognizedRevenueAccount == other.ContractRecognizedRevenueAccount ||
                    ContractRecognizedRevenueAccount != null &&
                    ContractRecognizedRevenueAccount.Equals(other.ContractRecognizedRevenueAccount)
                ) && 
                (
                    DeferredRevenueAccount == other.DeferredRevenueAccount ||
                    DeferredRevenueAccount != null &&
                    DeferredRevenueAccount.Equals(other.DeferredRevenueAccount)
                ) && 
                (
                    RecognizedRevenueAccount == other.RecognizedRevenueAccount ||
                    RecognizedRevenueAccount != null &&
                    RecognizedRevenueAccount.Equals(other.RecognizedRevenueAccount)
                ) && 
                (
                    RevenueRecognitionRuleName == other.RevenueRecognitionRuleName ||
                    RevenueRecognitionRuleName != null &&
                    RevenueRecognitionRuleName.Equals(other.RevenueRecognitionRuleName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ExcludeItemBillingFromRevenueAccounting != null)
                    hashCode = hashCode * 59 + ExcludeItemBillingFromRevenueAccounting.GetHashCode();
                    if (ExcludeItemBookingFromRevenueAccounting != null)
                    hashCode = hashCode * 59 + ExcludeItemBookingFromRevenueAccounting.GetHashCode();
                    if (AdjustmentRevenueAccount != null)
                    hashCode = hashCode * 59 + AdjustmentRevenueAccount.GetHashCode();
                    if (ContractRecognizedRevenueAccount != null)
                    hashCode = hashCode * 59 + ContractRecognizedRevenueAccount.GetHashCode();
                    if (DeferredRevenueAccount != null)
                    hashCode = hashCode * 59 + DeferredRevenueAccount.GetHashCode();
                    if (RecognizedRevenueAccount != null)
                    hashCode = hashCode * 59 + RecognizedRevenueAccount.GetHashCode();
                    if (RevenueRecognitionRuleName != null)
                    hashCode = hashCode * 59 + RevenueRecognitionRuleName.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(OrderLineItemRevenue left, OrderLineItemRevenue right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(OrderLineItemRevenue left, OrderLineItemRevenue right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
